name: "Build NetcraveOS"

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install grub EFI
      run: sudo apt update ; sudo apt -y install grub-efi
    - name: Create installer.bin
      run: truncate -s 600M installer.bin
    - name: Create installer.bin
      run: sudo mknod -m 0660 /dev/loop254 b 7 254
    - name: Mount installer.bin as loopback device
      run: sudo losetup -P /dev/loop254 installer.bin
    - name: Build base installer image
      run: chmod +x create-debian-usb-key.sh && sudo DEBIAN_RELEASE=$DEBIAN_RELEASE DEBIAN_VERSION=$DEBIAN_VERSION ARCH=$ARCH ./create-debian-usb-key.sh /dev/loop254
      env:
        DEBIAN_RELEASE: bullseye 
        DEBIAN_VERSION: 11.6.0 
        ARCH: amd64 
    - name: Add custom preseed.cfg
      run: sudo mount /dev/loop254p3 /mnt && sudo cp preseed.cfg /mnt/preseed && sudo umount /mnt
    - name: Disconnect installer.bin
      run: sudo losetup -d /dev/loop254 
    - name: sha256sum installer.bin
      run: sha256sum installer.bin > installer.bin.sha256sum 
    - name: Move into directory
      run:  mkdir netcrave_os_installer && mv installer.* netcrave_os_installer/
    - name: Archive directory
      run: zip -r netcrave_os_installer.zip netcrave_os_installer
    - name: Create GH release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: "latest"
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./netcrave_os_installer.zip
        asset_name: netcrave_os_installer.zip
        asset_content_type: application/zip
