name: Build NetcraveOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Create installer.bin
      run: truncate -s 512M installer.bin
    - name: Create installer.bin
      run: sudo mknod -m 0660 /dev/loop254 b 7 254
    - name: Mount installer.bin as loopback device
      run: sudo losetup -P /dev/loop254 installer.bin
    - name: Build base installer image
      run: chmod +x create-debian-usb-key.sh && sudo DEBIAN_RELEASE=$DEBIAN_RELEASE DEBIAN_VERSION=$DEBIAN_VERSION ARCH=$ARCH ./create-debian-usb-key.sh /dev/loop254
      env:
        DEBIAN_RELEASE: bullseye 
        DEBIAN_VERSION: 11.6.0 
        ARCH: amd64 
    - name: Add custom preseed.cfg
      run: sudo mount /dev/loop254p1 /mnt/usb && sudo cp preseed.cfg /mnt/usb/preseed && sudo umount /mnt/usb
    - name: Disconnect installer.bin
      run: sudo losetup -d /dev/loop254 
    - name: sha256sum installer.bin
      run: sha256sum installer.bin > installer.bin.sha256sum 
    - name: Move into directory
      run:  mkdir netcrave_os_installer && mv installer.* netcrave_os_installer/
    - uses: actions/upload-artifact@v3
      with:
        name: netcraveos-installer
        path: netcrave_os_installer
