name: "Build NetcraveOS"

on:
  workflow_dispatch:

env:
  DEBIAN_RELEASE: bullseye 
  DEBIAN_VERSION: 11.6.0 
  ARCH: amd64 

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install grub EFI
      run: sudo apt update ; sudo apt -y install grub-efi
    - name: Create installer.bin
      run: truncate -s 4700M installer.bin
    - name: Mount installer.bin as loopback device
      run: sudo losetup -fP installer.bin
    - name: Build base installer image
      run: chmod +x create-debian-usb-key.sh && sudo DEBIAN_RELEASE=$DEBIAN_RELEASE DEBIAN_VERSION=$DEBIAN_VERSION ARCH=$ARCH ./create-debian-usb-key.sh /dev/loop1
    - name: Add custom preseed.cfg
      run: sudo mount /dev/loop1p3 /mnt && sudo cp preseed.cfg /mnt/preseed 
    - name: Copy linux-firmware to image
      run: mkdir /mnt/linux-firmware && cp -rvp linux-firmware/* /mnt/linux-firmware
    - name: Unmount root fs 
      run: sudo umount /mnt
    - name: Disconnect installer.bin
      run: sudo losetup -d /dev/loop1
    - name: sha256sum installer.bin
      run: sha256sum installer.bin > installer.bin.sha256sum 
    - name: Move into directory
      run:  mkdir netcrave_os_installer && mv installer.* netcrave_os_installer/
    - name: Archive directory
      run: zip -r netcrave_os_installer.zip netcrave_os_installer
    - name: Create GH release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ env.DEBIAN_VERSION }}_${{ env.ARCH }}
        tag_name: ${{ env.DEBIAN_VERSION }}_${{ env.ARCH }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload zipped image to release artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./netcrave_os_installer.zip
        asset_name: netcrave_os_installer.zip
        asset_content_type: application/zip
